.TH cap.h 3 "16 Dec 1999" "simeb_ebit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cap.h \- 
.SH SYNOPSIS
.br
.PP
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBCAP_bGroup\fR"
.br
.ti -1c
.RI "#define \fBCAP_bAcceleration\fR"
.br
.ti -1c
.RI "#define \fBCAP_bRelativity\fR"
.br
.in -1c
.SH DEFINE DOCUMENTATION
.PP 
.SS #define CAP_bGroup ()
.PP
.SS #define CAP_bAcceleration ()
.PP
.SS #define CAP_bRelativity ()
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for simeb_ebit from the source code.