.TH illumin.h 3 "16 Dec 1999" "simeb_ebit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
illumin.h \- 
.SH SYNOPSIS
.br
.PP
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBTIllumin\fR"
.br
.ti -1c
.RI "class \fBTIlluminUniform\fR"
.br
.ti -1c
.RI "class \fBTIlluminLumped\fR"
.br
.ti -1c
.RI "class \fBTIlluminGaussian\fR"
.br
.ti -1c
.RI "class \fBTIlluminFixed\fR"
.br
.in -1c
.SH AUTHOR
.PP 
Generated automatically by Doxygen for simeb_ebit from the source code.