.TH include.h 3 "16 Dec 1999" "simeb_ebit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include.h \- 
.SH SYNOPSIS
.br
.PP
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBnewline\fR"
.br
.ti -1c
.RI "#define \fBspace\fR"
.br
.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "typedef double \fBreal\fR"
.br
.in -1c
.SH DEFINE DOCUMENTATION
.PP 
.SS #define newline ()
.PP
.SS #define space ()
.PP
.SH TYPEDEF DOCUMENTATION
.PP 
.SS typedef double real
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for simeb_ebit from the source code.