.TH plane.h 3 "16 Dec 1999" "simeb_ebit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plane.h \- 
.SH SYNOPSIS
.br
.PP
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBTPlane\fR"
.br
.ti -1c
.RI "class \fBTTarget\fR"
.br
.ti -1c
.RI "class \fBTAperture\fR"
.br
.ti -1c
.RI "class \fBTThinLens\fR"
.br
.ti -1c
.RI "class \fBEELens\fR"
.br
.in -1c
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBEELENS_OFF\fR"
.br
.ti -1c
.RI "#define \fBEELENS_TARGET\fR"
.br
.ti -1c
.RI "#define \fBEELENS_LENS\fR"
.br
.in -1c
.SH DEFINE DOCUMENTATION
.PP 
.SS #define EELENS_OFF ()
.PP
.SS #define EELENS_TARGET ()
.PP
.SS #define EELENS_LENS ()
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for simeb_ebit from the source code.