.TH Relativity 3 "16 Dec 1999" "simeb_ebit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Relativity \- 
.SH SYNOPSIS
.br
.PP
\fC#include <relativity.h>\fR
.PP
.SS Static Public Members

.in +1c
.ti -1c
.RI "void \fBrSetQM\fR (\fBreal\fR r_qm)"
.br
.ti -1c
.RI "const \fBreal\fR \fBrCalcVelocity\fR (\fBreal\fR r_voltage)"
.br
.ti -1c
.RI "const \fBreal\fR \fBrCalcVelocity\fR (\fBreal\fR r_voltage, \fBreal\fR r_alpha)"
.br
.ti -1c
.RI "const \fBreal\fR \fBrCalcVoltage\fR (\fBreal\fR r_velocity)"
.br
.ti -1c
.RI "const \fBreal\fR \fBrCalcGammaFromVelocity\fR (\fBreal\fR r_velocity)"
.br
.ti -1c
.RI "const \fBreal\fR \fBrCalcGammaFromVoltage\fR (\fBreal\fR r_voltage)"
.br
.ti -1c
.RI "\fBreal\fR \fBrQM\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS void Relativity::rSetQM (\fBreal\fR r_qm)\fC [inline, static]\fR
.PP
.SS const \fBreal\fR Relativity::rCalcVelocity (\fBreal\fR r_voltage)\fC [inline, static]\fR
.PP
.SS const \fBreal\fR Relativity::rCalcVelocity (\fBreal\fR r_voltage, \fBreal\fR r_alpha)\fC [inline, static]\fR
.PP
.SS const \fBreal\fR Relativity::rCalcVoltage (\fBreal\fR r_velocity)\fC [inline, static]\fR
.PP
.SS const \fBreal\fR Relativity::rCalcGammaFromVelocity (\fBreal\fR r_velocity)\fC [inline, static]\fR
.PP
.SS const \fBreal\fR Relativity::rCalcGammaFromVoltage (\fBreal\fR r_voltage)\fC [inline, static]\fR
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBreal\fR Relativity::rQM\fC [static]\fR
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for simeb_ebit from the source code.