.TH shape.h 3 "16 Dec 1999" "simeb_ebit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shape.h \- 
.SH SYNOPSIS
.br
.PP
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBTShape\fR"
.br
.ti -1c
.RI "class \fBTShapePoint\fR"
.br
.ti -1c
.RI "class \fBTShapeCircle\fR"
.br
.ti -1c
.RI "class \fBTShapeBagel\fR"
.br
.ti -1c
.RI "class \fBTShapeSquare\fR"
.br
.ti -1c
.RI "class \fBTShapeRectangle\fR"
.br
.in -1c
.SH AUTHOR
.PP 
Generated automatically by Doxygen for simeb_ebit from the source code.