.TH TAperture 3 "16 Dec 1999" "simeb_ebit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TAperture \- 
.SH SYNOPSIS
.br
.PP
\fC#include <plane.h>\fR
.PP
Inherits \fBTPlane\fR.
.PP
.SS Public Members

.in +1c
.ti -1c
.RI "\fBTAperture\fR ()"
.br
.ti -1c
.RI "virtual void \fBParse\fR (\fBTParser\fR &, char *)"
.br
.ti -1c
.RI "virtual bool \fBCross\fR (\fBParticle\fR * const p)"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS TAperture::TAperture ()
.PP
.SS void TAperture::Parse (\fBTParser\fR & parser, char * s_token)\fC [virtual]\fR
.PP
Reimplemented from \fBTPlane\fR.
.SS bool TAperture::Cross (\fBParticle\fR * const p)\fC [virtual]\fR
.PP
Reimplemented from \fBTPlane\fR.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for simeb_ebit from the source code.