.TH TArgParser 3 "16 Dec 1999" "simeb_ebit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TArgParser \- 
.SH SYNOPSIS
.br
.PP
\fC#include <setup.h>\fR
.PP
Inherits \fBTParser\fR.
.PP
.SS Public Members

.in +1c
.ti -1c
.RI "\fBTArgParser\fR (unsigned uargc, char const * const * argv)"
.br
.ti -1c
.RI "virtual bool \fBGetToken\fR (void)"
.br
.ti -1c
.RI "virtual void \fBError\fR (void)"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS TArgParser::TArgParser (unsigned u_argc, char const *const * s_argv)
.PP
.SS bool TArgParser::GetToken (void)\fC [virtual]\fR
.PP
Reimplemented from \fBTParser\fR.
.SS void TArgParser::Error (void)\fC [virtual]\fR
.PP
Reimplemented from \fBTParser\fR.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for simeb_ebit from the source code.