.TH TFileParser 3 "16 Dec 1999" "simeb_ebit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TFileParser \- 
.SH SYNOPSIS
.br
.PP
\fC#include <setup.h>\fR
.PP
Inherits \fBTParser\fR.
.PP
.SS Public Members

.in +1c
.ti -1c
.RI "\fBTFileParser\fR (char const *sfilename)"
.br
.ti -1c
.RI "virtual bool \fBGetToken\fR (void)"
.br
.ti -1c
.RI "virtual void \fBError\fR (void)"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS TFileParser::TFileParser (char const * s_filename)
.PP
.SS bool TFileParser::GetToken (void)\fC [virtual]\fR
.PP
Reimplemented from \fBTParser\fR.
.SS void TFileParser::Error (void)\fC [virtual]\fR
.PP
Reimplemented from \fBTParser\fR.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for simeb_ebit from the source code.