.TH TIlluminLumped 3 "16 Dec 1999" "simeb_ebit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIlluminLumped \- 
.SH SYNOPSIS
.br
.PP
\fC#include <illumin.h>\fR
.PP
Inherits \fBTIllumin\fR.
.PP
.SS Public Members

.in +1c
.ti -1c
.RI "\fBTIlluminLumped\fR (void)"
.br
.ti -1c
.RI "virtual void \fBParse\fR (\fBTParser\fR &, char *)"
.br
.ti -1c
.RI "virtual void \fBRandomize\fR (\fBParticle\fR *, \fBreal\fR)"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS TIlluminLumped::TIlluminLumped (void)
.PP
.SS void TIlluminLumped::Parse (\fBTParser\fR & parser, char * s_token)\fC [virtual]\fR
.PP
Reimplemented from \fBTIllumin\fR.
.SS void TIlluminLumped::Randomize (\fBParticle\fR * p, \fBreal\fR r_energy)\fC [virtual]\fR
.PP
Reimplemented from \fBTIllumin\fR.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for simeb_ebit from the source code.