.TH TSourceEELens 3 "16 Dec 1999" "simeb_ebit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TSourceEELens \- 
.SH SYNOPSIS
.br
.PP
\fC#include <source.h>\fR
.PP
Inherits \fBTSource\fR.
.PP
.SS Public Members

.in +1c
.ti -1c
.RI "\fBTSourceEELens\fR (void)"
.br
.ti -1c
.RI "virtual void \fBParse\fR (\fBTParser\fR &parser, char *)"
.br
.ti -1c
.RI "virtual void \fBInitialize\fR (void)"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS TSourceEELens::TSourceEELens (void)
.PP
.SS void TSourceEELens::Parse (\fBTParser\fR & parser, char * s_token)\fC [virtual]\fR
.PP
Reimplemented from \fBTPlane\fR.
.SS void TSourceEELens::Initialize (void)\fC [virtual]\fR
.PP
Reimplemented from \fBTPlane\fR.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for simeb_ebit from the source code.