.TH TSourceGrid 3 "16 Dec 1999" "simeb_ebit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TSourceGrid \- 
.SH SYNOPSIS
.br
.PP
\fC#include <source.h>\fR
.PP
Inherits \fBTSource\fR.
.PP
.SS Public Members

.in +1c
.ti -1c
.RI "\fBTSourceGrid\fR (void)"
.br
.ti -1c
.RI "virtual void \fBParse\fR (\fBTParser\fR &parser, char *)"
.br
.ti -1c
.RI "virtual void \fBInitialize\fR (void)"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS TSourceGrid::TSourceGrid (void)
.PP
.SS void TSourceGrid::Parse (\fBTParser\fR & parser, char * s_token)\fC [virtual]\fR
.PP
Reimplemented from \fBTPlane\fR.
.SS void TSourceGrid::Initialize (void)\fC [virtual]\fR
.PP
Reimplemented from \fBTPlane\fR.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for simeb_ebit from the source code.