.TH TXYZ 3 "16 Dec 1999" "simeb_ebit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TXYZ \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector.h>\fR
.PP
.SS Public Members

.in +1c
.ti -1c
.RI "\fBTXYZ\fR (\fBreal\fR rix = 0.0, \fBreal\fR riy = 0.0, \fBreal\fR riz = 0.0)"
.br
.ti -1c
.RI "\fBTXYZ\fR (const \fBTXY\fR &xy, \fBreal\fR riz = 0.0)"
.br
.ti -1c
.RI "TXYZ \fBoperator=\fR (const \fBTXY\fR &xy)"
.br
.ti -1c
.RI "\fBreal\fR \fBrX\fR"
.br
.ti -1c
.RI "\fBreal\fR \fBrY\fR"
.br
.ti -1c
.RI "\fBreal\fR \fBrZ\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS TXYZ::TXYZ (\fBreal\fR rix = 0.0, \fBreal\fR riy = 0.0, \fBreal\fR riz = 0.0)\fC [inline]\fR
.PP
.SS TXYZ::TXYZ (const \fBTXY\fR & xy, \fBreal\fR riz = 0.0)\fC [inline]\fR
.PP
.SS TXYZ TXYZ::operator= (const \fBTXY\fR & xy)\fC [inline]\fR
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBreal\fR TXYZ::rX
.PP
.SS \fBreal\fR TXYZ::rY
.PP
.SS \fBreal\fR TXYZ::rZ
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for simeb_ebit from the source code.